name: build

on:
  push:
    branches: [main]
  # TODO: is it necessary?
  workflow_dispatch:

# Looks like not necessary. Issue was in repository settings.
# permissions:
#   contents: read
#   id-token: write

jobs:
  build:
    secrets: inherit
    uses: oleksandrkudin/poc-ndp-workflows/.github/workflows/build.yaml@main
    with:
      # TODO: can be change with github.repository
      unit: "poc-ndp-helm-chart1"
      environment: dev
